server:
  port: 8080
spring:
  config:
    activate:
      on-profile: dev

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

open:
  api:
    title: ${API_TITLE:DUMMY_API_TITLE}
    version: v1.0.0
    description: This is the OpenAPI swagger for some specific API endpoints
    serverUrl: http://localhost:${server.port}
    serverName: Demo Server
