server.port=8081
spring.config.activate.on-profile=dev
open.api.title=API document
open.api.version=v1.0.0
open.api.description=This is the OpenAPI swagger for some specific API endpoints
open.api.serverUrl=http://localhost:${server.port}
open.api.serverName=Demo Server