server:
  port: 8080
spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
        ddl-auto: none

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

open:
  api:
    title: ${API_TITLE:DUMMY_API_TITLE}
    version: v1.0.0
    description: This is the OpenAPI swagger for some specific API endpoints
    serverUrl: http://localhost:${server.port}
    serverName: Demo Server
